name: Test

on:
  push:
    paths:
      - ".github/workflows/**"
      - ".npmrc"
      - ".releaserc.json"
      - "ava.config.js"
      - "package-lock.json"
      - "package.json"
      - "source/**"
      - "tsconfig.json"

permissions:
  contents: read

jobs:
  commits:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Action | Checkout repository code
        uses: actions/checkout@v6

      - name: Evaluate | Validate commit messages
        uses: opensource-nepal/commitlint@v1.13.3

  source-files:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Action | Checkout repository code
        uses: actions/checkout@v6

      - name: Setup | Configure Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "25"
          cache: "npm"

      - name: Setup | Install dependencies
        run: npm ci

      - name: Evaluate | Run tests
        run: npm run test
